Change weekInfo to express non-continouse weekend
tc39/proposal-intl-locale-info pull request #44
Opened 2021-09-07 23:20 UTC by FrankYFTang

Close #25

2021-09-07 23:34 UTC, sffc requested changes

2021-09-07 23:34 UTC, sffc commented on locale.html
> +            <td>The list of weekday values indicating which days of the week are considered as part of the 'weekend', for calendar purposes. Notice the number of days in weekend are different in each
```suggestion
            <td>The list of weekday values indicating which days of the week are considered as part of the 'weekend', for calendar purposes. Notice that the number of days in the weekend are different in each locale, and they may not be contiguous.</td>
```

2021-09-08 10:47 UTC, anba requested changes

2021-09-08 10:47 UTC, anba commented on annexes.html
> +          The 'first' day of a week, the minimal days required in the first week of a month or year, and days of the week are considered as part of the 'weekend', for calendar purposes, per locale (<
```suggestion
          The 'first' day of a week, the minimal days required in the first week of a month or year, and which days of the week are considered as part of the 'weekend', for calendar purposes, per locale (<emu-xref href="#sec-week-info-of-locale"></emu-xref>)
```

2021-09-08 10:47 UTC, anba commented on locale.html
> +            <td>The list of weekday values indicating which days of the week are considered as part of the 'weekend', for calendar purposes. Notice that the number of days in the weekend are differen
```suggestion
            <td>The list of weekday values indicating which days of the week are considered as part of the 'weekend', for calendar purposes. Notice that the number of days in the weekend are different in each locale and may not be contiguous.</td>
```

2021-09-08 10:47 UTC, anba commented on locale.html
> +            <td>A List of 1 or more Integer value between 1 and 7: 1 specifies Monday; 2 specifies Tuesday; 3 specifies Wednesday; 4 specifies Thursday; 5 specifies Friday; 6 specifies Saturday; and
````suggestion
            <td>A List of 1 or more integer values between 1 and 7: 1 specifies Monday; 2 specifies Tuesday; 3 specifies Wednesday; 4 specifies Thursday; 5 specifies Friday; 6 specifies Saturday; and 7 specifies Sunday.</td>
```

2021-09-08 10:47 UTC, anba commented on locale.html
> +        1. Let _dir_ be ! CharacterDirectionOfLocale(_loc_)
```suggestion
        1. Let _dir_ be ! CharacterDirectionOfLocale(_loc_).
```

2021-09-08 10:47 UTC, anba commented on locale.html
> +        1. Let _wi_ be ! WeekInfoOfLocale(_loc_)
```suggestion
        1. Let _wi_ be ! WeekInfoOfLocale(_loc_).
```

2021-09-09 17:24 UTC, sffc commented on README.md
> +// {firstDay: 7, weekend: [5, 7], minimalDays: 1}  // Burnie weekend is Friday and Sunday but not Saturday
```suggestion
// {firstDay: 7, weekend: [5, 7], minimalDays: 1}  // Brunei weekend is Friday and Sunday but not Saturday 
```

2021-09-09 19:41 UTC, sffc commented
This PR was approved in 2021-09-09 TC39-TG2, modulo the editorial review comments: https://github.com/tc39/ecma402/blob/master/meetings/notes-2021-09-09.md#change-weekinfo-to-express-non-continouse-sic-weekend

2021-09-09 21:34 UTC, merged