Editorial: Simplify CreateArrayFromListOrRestricted
tc39/proposal-intl-locale-info pull request #50
Opened 2021-09-09 22:30 UTC by FrankYFTang

address https://github.com/tc39/proposal-intl-locale-info/issues/45

@anba @sffc @zbraniecki @ryzokuken @gibson042

2021-09-10 07:10 UTC, anba requested changes

2021-09-10 07:10 UTC, anba commented on locale.html
> +        1. Return ! CreateArrayFromList(  &laquo; _restricted_ &raquo; ).
```suggestion
        1. Return ! CreateArrayFromList( _list_ ).
```

2021-09-10 07:10 UTC, anba commented on locale.html
> +          1. Set _list_ to _restricted_ .
```suggestion
          1. Set _list_ to &laquo; _restricted_ &raquo;.
```

2021-09-10 18:04 UTC, FrankYFTang commented
PTAL

2021-09-14 07:35 UTC, anba approved these changes
LGTM!

2021-10-07 16:28 UTC, merged